- id: cyan
  name: cyan
  description: "🩵 `black` with an opinion on good engineering practices"
  entry: cyan
  language: python
  minimum_pre_commit_version: 2.9.2
  require_serial: true
  types_or: [python, pyi]
