repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile=black]
  - repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
      - id: black
        name: black (python)
        language_version: python3.10
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: flake8
        name: flake8 (python)
        args:
          [
            "--max-line-length=88",
            "--ignore=E203,W503,E501,E704",
            "--per-file-ignores=__init__.py:F401",
          ]
  - repo: local
    hooks:
      - id: cyan
        name: cyan
        entry: poetry run cyan
        language: python
        files: \.(py)$
