- id: cyan
  name: cyan
  description: "🩵 `black` with an opinion on good engineering practices"
  entry: cyan
  stages: [commit, merge-commit, push, manual]
  require_serial: true
  language: python
  types_or: [cython, pyi, python]
  args: ["--filter-files"]
  minimum_pre_commit_version: "2.9.2"
